export const categories = [
  "background",
  "neck",
  "nose",
  "mouth",
  "ears",
  "hair",
  "eyes",
  "leg",
  "accessories",
];

export const choices = {
  background: [
    "blue50",
    "blue70",
    "darkblue50",
    "green50",
    "green70",
    "grey70",
    "red50",
    "red70",
    "yellow60",
    "blue60",
    "darkblue30",
    "darkblue70",
    "green60",
    "grey40",
    "grey80",
    "red60",
    "yellow50",
    "yellow70",
  ],
  neck: ["bend-backward", "bend-forward", "default", "thick"],
  nose: ["default"],
  mouth: ["astonished", "default", "eating", "laugh", "tongue"],
  ears: ["default", "tilt-backward", "tilt-forward"],
  hair: ["bang", "curls", "default", "elegant", "fancy", "quiff", "short"],
  eyes: ["angry", "default", "naughty", "panda", "smart", "star"],
  leg: [
    "bubble-tea",
    "cookie",
    "default",
    "game-console",
    "tilt-backward",
    "tilt-forward",
  ],
  accessories: ["earings", "flower", "glasses", "headphone"],
};
