import Alpaca from "components/Aplaca";
import Buttons from "components/Buttons";
import Categories from "components/Categories";
import Choices from "components/Choices";
import Head from "next/head";
import { useEffect, useRef } from "react";
import create from "zustand";

export const useStore = create((set) => ({
  category: "background",
  setCategory: (category) =>
    set((state) => ({
      category: category,
    })),

  alpaca: {
    background: "blue50",
    ears: "default",
    eyes: "default",
    hair: "default",
    leg: "default",
    mouth: "default",
    neck: "default",
    accessories: "glasses",
    nose: "default",
  },
  setAlpaca: (alpaca) => set((state) => ({ alpaca: alpaca })),
  alpacaRef: null,
  setAlpacaRef: (ref) =>
    set((state) => ({
      alpacaRef: ref,
    })),
}));

export default function Home() {
  const ref = useRef(null);
  const setAlpacaRef = useStore((state) => state.setAlpacaRef);

  useEffect(() => {
    setAlpacaRef(ref);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [ref]);
  return (
    <div className="App">
      <Head>
        <title>Alpacator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Categories />
      <Buttons />
      <main>
        <div>
          <Alpaca innerRef={ref} />
        </div>
        <Choices />
      </main>
    </div>
  );
}
